/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Conexion.CRUDCliente;
import Conexion.CRUDEmpleado;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import modelo.Persona;
import static vistas.RegistrarEmpleado.jTextFieldIDEmpleado;

/**
 *
 * @author HP
 */
public class PantallaRegistroReservacionEstancia extends javax.swing.JFrame {

    public PantallaRegistroReservacionEstancia() {
        initComponents();
        ButtonGroup grupoRadios = new ButtonGroup();
        grupoRadios.add(jRadioButtonReservacion);
        grupoRadios.add(jRadioButtonEstadia);

        jTextFieldPrecio.setEnabled(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src\\vistaimagen\\FondoHotel.jpg");

        llenarGarantias();
    }

    public void llenarGarantias() {
        CRUDEmpleado gr = new CRUDEmpleado();
        ArrayList<Empleado> listaEmpleados = gr.mostrarDatosCombo();
        jComboBoxEmpleado.removeAllItems();
        for (int i = 0; i < listaEmpleados.size(); i++) {
            jComboBoxEmpleado.addItem(new Empleado(
                    listaEmpleados.get(i).getID_Empleado(),
                    listaEmpleados.get(i).getNombre1()));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel4 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabelPrecio2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbuttonRegistrahabitacionNow = new javax.swing.JButton();
        labelHabitacion = new javax.swing.JLabel();
        jTextFieldClienteReser = new javax.swing.JTextField();
        labelcliente = new javax.swing.JLabel();
        jbuttonBuscarCliente = new javax.swing.JButton();
        labelcliente1 = new javax.swing.JLabel();
        jComboBoxEmpleado = new javax.swing.JComboBox<>();
        jRadioButtonReservacion = new javax.swing.JRadioButton();
        jRadioButtonEstadia = new javax.swing.JRadioButton();
        jTextFieldFechEntrada1 = new javax.swing.JTextField();
        jLabelFechaEntrada1 = new javax.swing.JLabel();
        jLabelFechaSalida = new javax.swing.JLabel();
        jTextFieldFechSalida = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelPrecio1 = new javax.swing.JLabel();
        jTextFieldPrecio1 = new javax.swing.JTextField();
        jComboBoxHabitacion = new javax.swing.JComboBox<>();
        jbuttonIrRegistroCliente = new javax.swing.JButton();
        jButtonRegistrarClient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel5.setBackground(new java.awt.Color(0, 94, 144));
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pagina Estancia/Reservaciones");
        panel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 630, -1));

        panel4.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 120));

        jPanel1.setBackground(new java.awt.Color(162, 179, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 430, 200));

        jPanel3.setBackground(new java.awt.Color(162, 179, 216));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrecio2.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        jLabelPrecio2.setText("Habitaciones");
        jPanel3.add(jLabelPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        panel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 450, 520));

        jPanel2.setBackground(new java.awt.Color(162, 179, 216));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbuttonRegistrahabitacionNow.setBackground(new java.awt.Color(216, 199, 162));
        jbuttonRegistrahabitacionNow.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbuttonRegistrahabitacionNow.setText("+");
        jbuttonRegistrahabitacionNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuttonRegistrahabitacionNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonRegistrahabitacionNowMouseClicked(evt);
            }
        });
        jbuttonRegistrahabitacionNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonRegistrahabitacionNowActionPerformed(evt);
            }
        });
        jPanel2.add(jbuttonRegistrahabitacionNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 38, -1, -1));

        labelHabitacion.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        labelHabitacion.setText("Habitacion");
        jPanel2.add(labelHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 39, -1, -1));

        jTextFieldClienteReser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldClienteReser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextFieldClienteReser, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 87, 200, 32));

        labelcliente.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        labelcliente.setText("Cliente");
        jPanel2.add(labelcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 90, -1, -1));

        jbuttonBuscarCliente.setBackground(new java.awt.Color(216, 199, 162));
        jbuttonBuscarCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbuttonBuscarCliente.setText("...");
        jbuttonBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuttonBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonBuscarClienteMouseClicked(evt);
            }
        });
        jbuttonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jbuttonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 89, -1, -1));

        labelcliente1.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        labelcliente1.setText("Empleado");
        jPanel2.add(labelcliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 133, -1, -1));

        jComboBoxEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEmpleadoItemStateChanged(evt);
            }
        });
        jComboBoxEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 131, 200, 32));

        jRadioButtonReservacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButtonReservacion.setText("Reservacion");
        jRadioButtonReservacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReservacionActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 194, -1, -1));

        jRadioButtonEstadia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButtonEstadia.setText("Estadia");
        jRadioButtonEstadia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstadiaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonEstadia, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 194, -1, -1));

        jTextFieldFechEntrada1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldFechEntrada1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jTextFieldFechEntrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 254, 200, 32));

        jLabelFechaEntrada1.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        jLabelFechaEntrada1.setText("Fecha Entrada");
        jPanel2.add(jLabelFechaEntrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 257, -1, -1));

        jLabelFechaSalida.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        jLabelFechaSalida.setText("Fecha Salida");
        jPanel2.add(jLabelFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 295, -1, -1));

        jTextFieldFechSalida.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldFechSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechSalidaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldFechSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 292, 200, 32));

        jTextFieldPrecio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 352, 200, 32));

        jLabelPrecio.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        jLabelPrecio.setText("Precio");
        jPanel2.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 355, -1, -1));

        jLabelPrecio1.setFont(new java.awt.Font("Roboto", 2, 20)); // NOI18N
        jLabelPrecio1.setText("Estado Reserva");
        jPanel2.add(jLabelPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 411, -1, -1));

        jTextFieldPrecio1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextFieldPrecio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecio1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 402, 200, 32));

        jComboBoxHabitacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxHabitacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHabitacionItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBoxHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 37, 200, 32));

        jbuttonIrRegistroCliente.setBackground(new java.awt.Color(216, 199, 162));
        jbuttonIrRegistroCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbuttonIrRegistroCliente.setText("+");
        jbuttonIrRegistroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuttonIrRegistroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonIrRegistroClienteMouseClicked(evt);
            }
        });
        jbuttonIrRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonIrRegistroClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jbuttonIrRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 89, -1, -1));

        jButtonRegistrarClient.setBackground(new java.awt.Color(216, 199, 162));
        jButtonRegistrarClient.setFont(new java.awt.Font("Roboto", 2, 16)); // NOI18N
        jButtonRegistrarClient.setText("Registrar");
        jButtonRegistrarClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarClientActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegistrarClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 100, 30));

        panel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 560, 520));

        jLabel2.setText("jLabel10");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1600, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarClientActionPerformed

    private void jbuttonRegistrahabitacionNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonRegistrahabitacionNowMouseClicked

    }//GEN-LAST:event_jbuttonRegistrahabitacionNowMouseClicked

    private void jbuttonRegistrahabitacionNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonRegistrahabitacionNowActionPerformed
//        
    }//GEN-LAST:event_jbuttonRegistrahabitacionNowActionPerformed


    private void jRadioButtonReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReservacionActionPerformed


    }//GEN-LAST:event_jRadioButtonReservacionActionPerformed

    private void jRadioButtonEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstadiaActionPerformed

    }//GEN-LAST:event_jRadioButtonEstadiaActionPerformed

    private void jbuttonBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonBuscarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonBuscarClienteMouseClicked

    private void jbuttonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonBuscarClienteActionPerformed
        PantallaBusquedaCliente BusCl = new PantallaBusquedaCliente();
        BusCl.setVisible(true);
        PantallaBusquedaCliente.jtextButtonAggCliReser.setVisible(true);
        PantallaBusquedaCliente.jtextButtonAggCliReser.setEnabled(true);
        PantallaBusquedaCliente.jbuttonEditar.setVisible(false);
        PantallaBusquedaCliente.jbuttonEliminar.setVisible(false);
        PantallaBusquedaCliente.jtextButtonRefresh.setVisible(false);
    }//GEN-LAST:event_jbuttonBuscarClienteActionPerformed

    private void jTextFieldFechSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechSalidaActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecio1ActionPerformed

    private void jComboBoxEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEmpleadoItemStateChanged

    }//GEN-LAST:event_jComboBoxEmpleadoItemStateChanged

    private void jComboBoxHabitacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHabitacionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHabitacionItemStateChanged

    private void jbuttonIrRegistroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonIrRegistroClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonIrRegistroClienteMouseClicked

    private void jbuttonIrRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonIrRegistroClienteActionPerformed
        PantallaClienteRegistro Cli = new PantallaClienteRegistro();
        Cli.setVisible(true);
        PantallaClienteRegistro.jButtonActualizar.setVisible(false);
    }//GEN-LAST:event_jbuttonIrRegistroClienteActionPerformed

    private void jComboBoxEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroReservacionEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroReservacionEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroReservacionEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistroReservacionEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistroReservacionEstancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarClient;
    private javax.swing.JComboBox<Empleado> jComboBoxEmpleado;
    private javax.swing.JComboBox<String> jComboBoxHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFechaEntrada1;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecio1;
    private javax.swing.JLabel jLabelPrecio2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonEstadia;
    private javax.swing.JRadioButton jRadioButtonReservacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextFieldClienteReser;
    private javax.swing.JTextField jTextFieldFechEntrada1;
    private javax.swing.JTextField jTextFieldFechSalida;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldPrecio1;
    private javax.swing.JButton jbuttonBuscarCliente;
    private javax.swing.JButton jbuttonIrRegistroCliente;
    private javax.swing.JButton jbuttonRegistrahabitacionNow;
    private javax.swing.JLabel labelHabitacion;
    private javax.swing.JLabel labelcliente;
    private javax.swing.JLabel labelcliente1;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    // End of variables declaration//GEN-END:variables
}
